INFO 2023-09-29 02:27:44,052 autoreload 6197 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 02:27:48,349 basehttp 6197 6126907392 "GET / HTTP/1.1" 200 13
INFO 2023-09-29 02:29:27,978 autoreload 6197 8539431040 /Users/aleksey/Desktop/Django/Seminar/myproject/settings.py changed, reloading.
INFO 2023-09-29 02:29:28,342 autoreload 6322 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 02:32:26,651 autoreload 6322 8539431040 /Users/aleksey/Desktop/Django/Seminar/myproject/settings.py changed, reloading.
INFO 2023-09-29 02:32:26,993 autoreload 6506 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 02:33:43,399 autoreload 6506 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-09-29 02:33:43,756 autoreload 6597 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 02:35:19,372 autoreload 6597 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-09-29 02:35:19,734 autoreload 6714 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 02:39:25,364 autoreload 6714 8539431040 /Users/aleksey/Desktop/Django/Seminar/myproject/settings.py changed, reloading.
INFO 2023-09-29 02:39:25,720 autoreload 6988 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 05:32:03,198 autoreload 16380 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 05:32:20,257 autoreload 16406 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 05:32:22,841 basehttp 16406 6165524480 "GET / HTTP/1.1" 200 13
INFO 2023-09-29 05:32:34,428 views 16406 6165524480 Result: Сторона: reshka, время: 2023-09-29 05:32:34.423478+00:00
INFO 2023-09-29 05:32:34,432 basehttp 16406 6165524480 "GET /eagle/ HTTP/1.1" 200 68
INFO 2023-09-29 05:32:44,189 views 16406 6165524480 Result: Сторона: reshka, время: 2023-09-29 05:32:44.187546+00:00
INFO 2023-09-29 05:32:44,190 basehttp 16406 6165524480 "GET /eagle/ HTTP/1.1" 200 68
INFO 2023-09-29 05:32:47,406 views 16406 6165524480 Result: Сторона: reshka, время: 2023-09-29 05:32:47.404387+00:00
INFO 2023-09-29 05:32:47,407 basehttp 16406 6165524480 "GET /eagle/ HTTP/1.1" 200 68
INFO 2023-09-29 05:33:49,113 autoreload 16406 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-09-29 05:33:49,459 autoreload 16541 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 05:33:58,728 autoreload 16541 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-09-29 05:33:59,040 autoreload 16561 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 05:34:02,712 views 16561 6191394816 Result: Сторона: reshka, время: 2023-09-29 05:34:02.709348+00:00
INFO 2023-09-29 05:34:02,713 basehttp 16561 6191394816 "GET /eagle/ HTTP/1.1" 200 68
INFO 2023-09-29 05:34:05,818 views 16561 6191394816 Result: Сторона: orel, время: 2023-09-29 05:34:05.815302+00:00
INFO 2023-09-29 05:34:05,819 basehttp 16561 6191394816 "GET /eagle/ HTTP/1.1" 200 66
INFO 2023-09-29 06:18:09,666 autoreload 19845 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:19:20,656 autoreload 19845 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:19:20,962 autoreload 19925 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:19:33,147 autoreload 19925 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:19:33,393 autoreload 19951 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:19:55,369 autoreload 19976 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:20:13,164 autoreload 20004 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:20:15,188 basehttp 20004 6201470976 "GET / HTTP/1.1" 200 13
INFO 2023-09-29 06:20:19,069 basehttp 20004 6201470976 "GET / HTTP/1.1" 200 13
WARNING 2023-09-29 06:20:25,221 log 20004 6201470976 Not Found: /show_elements
WARNING 2023-09-29 06:20:25,222 basehttp 20004 6201470976 "GET /show_elements HTTP/1.1" 404 2992
INFO 2023-09-29 06:20:54,061 basehttp 20004 6201470976 "GET / HTTP/1.1" 200 13
WARNING 2023-09-29 06:20:54,687 log 20004 6201470976 Not Found: /show_elements
WARNING 2023-09-29 06:20:54,688 basehttp 20004 6201470976 "GET /show_elements HTTP/1.1" 404 2992
INFO 2023-09-29 06:21:26,948 basehttp 20004 6201470976 "GET /show_elements/3 HTTP/1.1" 301 0
INFO 2023-09-29 06:21:26,962 basehttp 20004 6201470976 "GET /show_elements/3/ HTTP/1.1" 200 232
INFO 2023-09-29 06:23:09,396 autoreload 20004 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:23:09,677 autoreload 20204 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:23:44,328 autoreload 20204 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:23:44,661 autoreload 20244 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:26:31,326 basehttp 20244 6200799232 "GET / HTTP/1.1" 200 13
INFO 2023-09-29 06:26:31,604 autoreload 20244 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:26:31,885 autoreload 20429 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:26:39,186 basehttp 20429 6171570176 "GET /show_elements/3/ HTTP/1.1" 200 214
INFO 2023-09-29 06:27:55,493 autoreload 20429 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:27:55,772 autoreload 20520 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:28:01,960 basehttp 20520 6137294848 "GET /show_elements/3/ HTTP/1.1" 200 226
INFO 2023-09-29 06:29:17,395 autoreload 20520 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:29:17,688 autoreload 20628 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:29:23,563 basehttp 20628 6155726848 "GET /show_elements/3/ HTTP/1.1" 200 226
INFO 2023-09-29 06:32:00,021 basehttp 20628 6155726848 "GET /show_elements/3/ HTTP/1.1" 200 226
INFO 2023-09-29 06:36:04,076 autoreload 20628 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:36:04,377 autoreload 21029 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:36:40,011 autoreload 21029 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:36:40,291 autoreload 21083 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:36:48,597 basehttp 21083 6132297728 "GET /show_elements/3/ HTTP/1.1" 200 412
INFO 2023-09-29 06:37:22,317 autoreload 21083 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:37:22,674 autoreload 21130 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:37:26,278 basehttp 21130 6166245376 "GET /show_elements/3/ HTTP/1.1" 200 403
INFO 2023-09-29 06:37:59,534 autoreload 21130 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:37:59,841 autoreload 21170 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:38:08,570 basehttp 21170 6203273216 "GET /show_elements/3/ HTTP/1.1" 200 404
INFO 2023-09-29 06:47:48,648 autoreload 21170 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:47:48,935 autoreload 21795 8539431040 Watching for file changes with StatReloader
ERROR 2023-09-29 06:47:56,611 log 21795 6168129536 Internal Server Error: /show_elements/3/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/games_app/views.py", line 23, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/models.py", line 16, in counter
    coins = Coin.objects.all()[-n:]
            ~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/db/models/query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2023-09-29 06:47:56,613 basehttp 21795 6168129536 "GET /show_elements/3/ HTTP/1.1" 500 66875
INFO 2023-09-29 06:49:18,695 autoreload 21795 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:49:18,968 autoreload 21898 8539431040 Watching for file changes with StatReloader
ERROR 2023-09-29 06:49:26,002 log 21898 6134689792 Internal Server Error: /show_elements/3/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/games_app/views.py", line 23, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/models.py", line 19, in counter
    if coin.is_eagle == 'orel':
       ^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'is_eagle'
ERROR 2023-09-29 06:49:26,003 basehttp 21898 6134689792 "GET /show_elements/3/ HTTP/1.1" 500 64030
INFO 2023-09-29 06:50:14,011 autoreload 21898 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:50:14,334 autoreload 21964 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:51:15,577 autoreload 21964 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:51:15,930 autoreload 22038 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:51:19,145 basehttp 22038 6197555200 "GET /show_elements/3/ HTTP/1.1" 200 24
INFO 2023-09-29 06:53:50,854 autoreload 22038 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 06:53:51,127 autoreload 22206 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 06:53:57,206 basehttp 22206 6159396864 "GET /show_elements/3/ HTTP/1.1" 200 24
INFO 2023-09-29 07:00:19,190 autoreload 22206 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 07:00:19,523 autoreload 22607 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 07:02:14,631 autoreload 22607 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 07:02:14,921 autoreload 22737 8539431040 Watching for file changes with StatReloader
INFO 2023-09-29 07:02:18,087 autoreload 22737 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-09-29 07:02:18,250 autoreload 22750 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 01:32:30,264 autoreload 51283 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 01:32:35,575 views 51283 6130380800 Result: home page access!
ERROR 2023-10-01 01:32:35,621 log 51283 6130380800 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp/views.py", line 15, in index
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-01 01:32:35,680 basehttp 51283 6130380800 "GET / HTTP/1.1" 500 73850
WARNING 2023-10-01 01:32:35,951 log 51283 6147207168 Not Found: /apple-touch-icon-precomposed.png
WARNING 2023-10-01 01:32:35,952 basehttp 51283 6147207168 "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 3215
WARNING 2023-10-01 01:32:35,976 log 51283 6147207168 Not Found: /apple-touch-icon.png
WARNING 2023-10-01 01:32:35,977 basehttp 51283 6147207168 "GET /apple-touch-icon.png HTTP/1.1" 404 3179
WARNING 2023-10-01 01:32:56,455 log 51283 6130380800 Not Found: /myapp
WARNING 2023-10-01 01:32:56,455 basehttp 51283 6130380800 "GET /myapp HTTP/1.1" 404 3134
WARNING 2023-10-01 01:33:13,628 log 51283 6130380800 Not Found: /myapp/
WARNING 2023-10-01 01:33:13,628 basehttp 51283 6130380800 "GET /myapp/ HTTP/1.1" 404 3137
WARNING 2023-10-01 01:33:19,019 log 51283 6130380800 Not Found: /myapp/about
WARNING 2023-10-01 01:33:19,020 basehttp 51283 6130380800 "GET /myapp/about HTTP/1.1" 404 3152
WARNING 2023-10-01 01:33:25,663 log 51283 6130380800 Not Found: /myapp/about/
WARNING 2023-10-01 01:33:25,664 basehttp 51283 6130380800 "GET /myapp/about/ HTTP/1.1" 404 3155
WARNING 2023-10-01 01:33:36,197 log 51283 6130380800 Not Found: /myapp/eagle
WARNING 2023-10-01 01:33:36,198 basehttp 51283 6130380800 "GET /myapp/eagle HTTP/1.1" 404 3152
INFO 2023-10-01 01:33:43,240 views 51283 6130380800 Result: about page access
ERROR 2023-10-01 01:33:43,269 log 51283 6130380800 Internal Server Error: /about
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp/views.py", line 23, in about
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-01 01:33:43,271 basehttp 51283 6130380800 "GET /about HTTP/1.1" 500 73020
INFO 2023-10-01 01:35:06,669 autoreload 51476 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 01:35:09,151 views 51476 6165950464 Result: home page access!
ERROR 2023-10-01 01:35:09,175 log 51476 6165950464 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp/views.py", line 15, in index
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-01 01:35:09,176 basehttp 51476 6165950464 "GET / HTTP/1.1" 500 73850
INFO 2023-10-01 01:35:53,369 autoreload 51561 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 01:35:54,311 views 51561 6200045568 Result: home page access!
INFO 2023-10-01 01:35:54,314 basehttp 51561 6200045568 "GET / HTTP/1.1" 200 567
INFO 2023-10-01 01:36:02,563 views 51561 6200045568 Result: about page access
INFO 2023-10-01 01:36:02,564 basehttp 51561 6200045568 "GET /about HTTP/1.1" 200 568
INFO 2023-10-01 01:36:25,059 autoreload 51561 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp/views.py changed, reloading.
INFO 2023-10-01 01:36:25,418 autoreload 51602 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 01:36:31,644 views 51602 6121730048 Result: about page access
INFO 2023-10-01 01:36:31,649 basehttp 51602 6121730048 "GET /about HTTP/1.1" 200 373
INFO 2023-10-01 01:36:33,595 views 51602 6121730048 Result: about page access
INFO 2023-10-01 01:36:33,597 basehttp 51602 6121730048 "GET /about HTTP/1.1" 200 373
INFO 2023-10-01 01:37:31,780 views 51602 6121730048 Result: about page access
INFO 2023-10-01 01:37:31,783 basehttp 51602 6121730048 "GET /about HTTP/1.1" 200 373
INFO 2023-10-01 11:26:56,247 autoreload 54890 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 11:26:59,085 views 54890 6160658432 Result: home page access!
INFO 2023-10-01 11:26:59,092 basehttp 54890 6160658432 "GET / HTTP/1.1" 200 571
INFO 2023-10-01 11:27:08,673 views 54890 6160658432 Result: about page access
INFO 2023-10-01 11:27:08,682 basehttp 54890 6160658432 "GET /about HTTP/1.1" 200 573
INFO 2023-10-01 11:49:36,119 autoreload 54890 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-01 11:49:36,557 autoreload 56370 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 11:50:09,714 autoreload 56427 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 11:50:45,871 autoreload 56476 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 11:51:24,166 autoreload 56534 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 11:51:27,008 views 56534 6165377024 Result: home page access!
INFO 2023-10-01 11:51:27,013 basehttp 56534 6165377024 "GET / HTTP/1.1" 200 578
INFO 2023-10-01 11:51:35,206 basehttp 56534 6165377024 "GET /eagle/6 HTTP/1.1" 200 673
INFO 2023-10-01 12:03:19,957 autoreload 56534 8539431040 /Users/aleksey/Desktop/Django/Seminar/myproject/urls.py changed, reloading.
INFO 2023-10-01 12:03:20,341 autoreload 57337 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:04:27,292 autoreload 57337 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-01 12:04:27,650 autoreload 57432 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:05:35,600 autoreload 57432 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-01 12:05:35,947 autoreload 57523 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:05:51,217 autoreload 57523 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-01 12:05:51,517 autoreload 57556 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:05:59,615 views 57556 6156054528 Result: home page access!
INFO 2023-10-01 12:05:59,624 basehttp 57556 6156054528 "GET / HTTP/1.1" 200 578
WARNING 2023-10-01 12:06:07,976 log 57556 6156054528 Not Found: /articles/2
WARNING 2023-10-01 12:06:07,977 basehttp 57556 6156054528 "GET /articles/2 HTTP/1.1" 404 3361
WARNING 2023-10-01 12:06:33,379 log 57556 6156054528 Not Found: /articles/2
WARNING 2023-10-01 12:06:33,380 basehttp 57556 6156054528 "GET /articles/2 HTTP/1.1" 404 3361
INFO 2023-10-01 12:07:05,077 autoreload 57556 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-01 12:07:05,426 autoreload 57638 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:07:06,739 views 57638 6190116864 Result: home page access!
INFO 2023-10-01 12:07:06,743 basehttp 57638 6190116864 "GET / HTTP/1.1" 200 578
INFO 2023-10-01 12:07:12,361 basehttp 57638 6190116864 "GET /articles/2 HTTP/1.1" 200 0
INFO 2023-10-01 12:07:16,493 basehttp 57638 6190116864 "GET /articles/2 HTTP/1.1" 200 0
INFO 2023-10-01 12:14:56,026 autoreload 58133 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:14:57,831 views 58133 6134525952 Result: home page access!
INFO 2023-10-01 12:14:57,834 basehttp 58133 6134525952 "GET / HTTP/1.1" 200 578
INFO 2023-10-01 12:15:01,522 basehttp 58133 6134525952 "GET /articles/2 HTTP/1.1" 200 574
INFO 2023-10-01 12:15:09,381 basehttp 58133 6134525952 "GET /articles/2 HTTP/1.1" 200 574
INFO 2023-10-01 12:16:27,705 autoreload 58133 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-01 12:16:28,068 autoreload 58267 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:16:30,983 views 58267 6162608128 Result: home page access!
INFO 2023-10-01 12:16:30,988 basehttp 58267 6162608128 "GET / HTTP/1.1" 200 578
INFO 2023-10-01 12:16:34,459 basehttp 58267 6162608128 "GET /articles/2 HTTP/1.1" 200 574
INFO 2023-10-01 12:17:37,397 autoreload 58267 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-01 12:17:37,755 autoreload 58385 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:17:43,079 basehttp 58385 6188920832 "GET /articles/2 HTTP/1.1" 200 574
INFO 2023-10-01 12:17:58,287 autoreload 58385 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-01 12:17:58,611 autoreload 58420 8539431040 Watching for file changes with StatReloader
INFO 2023-10-01 12:18:05,836 basehttp 58420 6126972928 "GET /articles/2 HTTP/1.1" 200 574
INFO 2023-10-01 12:19:14,771 basehttp 58420 6126972928 "GET /articles/6 HTTP/1.1" 200 725
INFO 2023-10-01 12:19:39,320 autoreload 58420 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-01 12:19:39,712 autoreload 58595 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:11:43,371 autoreload 67058 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:11:45,431 views 67058 6133805056 Result: home page access!
INFO 2023-10-02 02:11:45,434 basehttp 67058 6133805056 "GET / HTTP/1.1" 200 578
ERROR 2023-10-02 02:11:52,808 log 67058 6133805056 Internal Server Error: /articles/6
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 14, in get_articles
    return render(request, 'myapp/index.html', context=articles)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/context.py", line 278, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
ERROR 2023-10-02 02:11:52,809 basehttp 67058 6133805056 "GET /articles/6 HTTP/1.1" 500 89262
INFO 2023-10-02 02:12:24,203 autoreload 67134 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:12:25,628 views 67134 6171635712 Result: home page access!
INFO 2023-10-02 02:12:25,631 basehttp 67134 6171635712 "GET / HTTP/1.1" 200 578
ERROR 2023-10-02 02:12:29,367 log 67134 6171635712 Internal Server Error: /articles/6
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 14, in get_articles
    return render(request, 'myapp/index.html', context=articles)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/context.py", line 278, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
ERROR 2023-10-02 02:12:29,368 basehttp 67134 6171635712 "GET /articles/6 HTTP/1.1" 500 89262
ERROR 2023-10-02 02:12:38,584 log 67134 6171635712 Internal Server Error: /articles/6
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 14, in get_articles
    return render(request, 'myapp/index.html', context=articles)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/context.py", line 278, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
ERROR 2023-10-02 02:12:38,585 basehttp 67134 6171635712 "GET /articles/6 HTTP/1.1" 500 89262
INFO 2023-10-02 02:13:25,406 autoreload 67134 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:13:25,693 autoreload 67205 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:13:27,270 views 67205 6201077760 Result: home page access!
INFO 2023-10-02 02:13:27,272 basehttp 67205 6201077760 "GET / HTTP/1.1" 200 578
INFO 2023-10-02 02:13:30,029 basehttp 67205 6201077760 "GET /articles/6 HTTP/1.1" 200 725
INFO 2023-10-02 02:25:47,901 autoreload 68238 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:25:49,154 views 68238 6125727744 Result: home page access!
INFO 2023-10-02 02:25:49,157 basehttp 68238 6125727744 "GET / HTTP/1.1" 200 607
ERROR 2023-10-02 02:25:52,268 log 68238 6125727744 Internal Server Error: /articles/6
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 14, in get_articles
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles_full' not found. 'articles_full' is not a valid view function or pattern name.
ERROR 2023-10-02 02:25:52,274 basehttp 68238 6125727744 "GET /articles/6 HTTP/1.1" 500 241773
INFO 2023-10-02 02:26:40,668 autoreload 68319 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:26:41,706 views 68319 6165393408 Result: home page access!
INFO 2023-10-02 02:26:41,709 basehttp 68319 6165393408 "GET / HTTP/1.1" 200 607
INFO 2023-10-02 02:26:45,098 basehttp 68319 6165393408 "GET /articles/6 HTTP/1.1" 200 1796
INFO 2023-10-02 02:29:21,777 basehttp 68319 6165393408 "GET /articles/6 HTTP/1.1" 200 1520
INFO 2023-10-02 02:29:35,964 basehttp 68319 6165393408 "GET /articles/6 HTTP/1.1" 200 2171
INFO 2023-10-02 02:37:02,076 autoreload 68319 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-02 02:37:02,362 autoreload 69123 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:37:36,993 autoreload 69123 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:37:37,335 autoreload 69189 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:38:58,514 autoreload 69189 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:38:58,801 autoreload 69315 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:39:26,335 autoreload 69315 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:39:26,602 autoreload 69357 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:42:02,055 views 69357 6170292224 Result: home page access!
INFO 2023-10-02 02:42:02,059 basehttp 69357 6170292224 "GET / HTTP/1.1" 200 607
INFO 2023-10-02 02:42:05,167 basehttp 69357 6170292224 "GET /articles/6 HTTP/1.1" 200 2203
INFO 2023-10-02 02:42:06,710 basehttp 69357 6170292224 "GET /detail/2 HTTP/1.1" 200 573
ERROR 2023-10-02 02:44:57,652 log 69357 6170292224 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 22, in detail_articles
    return render(request, 'myapp/about.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{ description' from '{ description'
ERROR 2023-10-02 02:44:57,656 basehttp 69357 6170292224 "GET /detail/2 HTTP/1.1" 500 162446
ERROR 2023-10-02 02:45:04,346 log 69357 6170292224 Internal Server Error: /detail/3
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 22, in detail_articles
    return render(request, 'myapp/about.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{ description' from '{ description'
ERROR 2023-10-02 02:45:04,350 basehttp 69357 6170292224 "GET /detail/3 HTTP/1.1" 500 162446
INFO 2023-10-02 02:45:19,003 basehttp 69357 6170292224 "GET /detail/3 HTTP/1.1" 200 604
INFO 2023-10-02 02:45:26,008 basehttp 69357 6170292224 "GET /detail/3 HTTP/1.1" 200 604
INFO 2023-10-02 02:46:18,610 basehttp 69357 6170292224 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:46:27,469 basehttp 69357 6170292224 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:46:33,241 basehttp 69357 6170292224 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:46:57,280 autoreload 69357 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:46:57,566 autoreload 69940 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:46:59,922 basehttp 69940 6159446016 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:47:26,247 autoreload 69940 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:47:26,489 autoreload 69990 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:47:26,820 basehttp 69990 6203944960 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:47:30,708 basehttp 69990 6203944960 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:47:37,730 basehttp 69990 6203944960 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:47:42,457 basehttp 69990 6203944960 "GET /detail/4 HTTP/1.1" 200 604
INFO 2023-10-02 02:50:32,028 autoreload 69990 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:50:32,420 autoreload 70211 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:50:36,609 basehttp 70211 6156185600 "GET /articles/6 HTTP/1.1" 200 2203
INFO 2023-10-02 02:50:38,188 basehttp 70211 6156185600 "GET /detail/2 HTTP/1.1" 200 604
INFO 2023-10-02 02:52:21,687 autoreload 70211 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:52:21,955 autoreload 70385 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:52:24,489 basehttp 70385 6132002816 "GET /detail/2 HTTP/1.1" 200 610
INFO 2023-10-02 02:52:40,755 basehttp 70385 6132002816 "GET /detail/2 HTTP/1.1" 200 686
INFO 2023-10-02 02:53:54,766 autoreload 70385 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:53:55,046 autoreload 70551 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 02:54:02,679 log 70551 6135377920 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    articles.view += 1
    ^^^^^^^^^^^^^
AttributeError: 'Article' object has no attribute 'view'
ERROR 2023-10-02 02:54:02,680 basehttp 70551 6135377920 "GET /detail/2 HTTP/1.1" 500 59567
INFO 2023-10-02 02:56:31,221 autoreload 70551 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 02:56:31,500 autoreload 70789 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 02:56:31,898 basehttp 70789 6190067712 "GET /detail/2 HTTP/1.1" 200 686
INFO 2023-10-02 02:56:35,480 basehttp 70789 6190067712 "GET /detail/2 HTTP/1.1" 200 686
INFO 2023-10-02 03:00:06,861 autoreload 70789 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:00:07,257 autoreload 71079 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:00:42,936 autoreload 71079 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:00:43,270 autoreload 71136 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:00:47,464 autoreload 71136 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:00:47,788 autoreload 71161 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:01:47,649 autoreload 71161 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:01:48,082 autoreload 71263 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:02:11,653 autoreload 71263 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:02:11,985 autoreload 71319 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:02:49,790 autoreload 71319 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/models.py changed, reloading.
INFO 2023-10-02 03:02:50,215 autoreload 71386 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:19:24,421 autoreload 72710 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 03:19:31,666 log 72710 6196801536 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id)
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:19:31,666 basehttp 72710 6196801536 "GET /detail/2 HTTP/1.1" 500 59677
WARNING 2023-10-02 03:20:30,506 log 72710 6196801536 Not Found: /detail
WARNING 2023-10-02 03:20:30,507 basehttp 72710 6196801536 "GET /detail HTTP/1.1" 404 3548
ERROR 2023-10-02 03:20:37,054 log 72710 6196801536 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id)
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:20:37,055 basehttp 72710 6196801536 "GET /detail/2 HTTP/1.1" 500 59677
INFO 2023-10-02 03:20:50,083 autoreload 72710 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:20:50,435 autoreload 72844 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 03:20:54,041 log 72844 6193950720 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 25, in detail_articles
    'comments': comments
                ^^^^^^^^
NameError: name 'comments' is not defined
ERROR 2023-10-02 03:20:54,042 basehttp 72844 6193950720 "GET /detail/2 HTTP/1.1" 500 58990
INFO 2023-10-02 03:21:07,938 autoreload 72844 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:21:08,253 autoreload 72891 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:21:08,877 basehttp 72891 6205108224 "GET /detail/2 HTTP/1.1" 200 710
INFO 2023-10-02 03:22:04,807 basehttp 72891 6205108224 "GET /detail/2 HTTP/1.1" 200 719
INFO 2023-10-02 03:22:31,675 autoreload 72891 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:22:32,052 autoreload 73000 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:25:38,527 autoreload 73000 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:25:38,909 autoreload 73290 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:26:03,449 autoreload 73290 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:26:03,778 autoreload 73327 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 03:28:33,320 log 73327 6159085568 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id).order_by('-change_at')
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:28:33,321 basehttp 73327 6159085568 "GET /detail/2 HTTP/1.1" 500 59743
INFO 2023-10-02 03:30:25,380 basehttp 73327 6159085568 "GET /articles/6 HTTP/1.1" 200 2203
ERROR 2023-10-02 03:30:36,388 log 73327 6159085568 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id).order_by('-change_at')
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:30:36,389 basehttp 73327 6159085568 "GET /detail/2 HTTP/1.1" 500 59904
ERROR 2023-10-02 03:31:58,715 log 73327 6159085568 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id).order_by('-change_at')
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:31:58,716 basehttp 73327 6159085568 "GET /detail/2 HTTP/1.1" 500 59743
INFO 2023-10-02 03:32:51,267 autoreload 73798 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 03:32:54,850 log 73798 6196555776 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter(article_id=article_id).order_by('-change_at')
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:32:54,851 basehttp 73798 6196555776 "GET /detail/2 HTTP/1.1" 500 59743
INFO 2023-10-02 03:33:14,790 autoreload 73798 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:33:15,173 autoreload 73832 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-02 03:33:15,694 log 73832 6190477312 Internal Server Error: /detail/2
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 19, in detail_articles
    comments = Comment.object.filter()
               ^^^^^^^^^^^^^^
AttributeError: type object 'Comment' has no attribute 'object'
ERROR 2023-10-02 03:33:15,695 basehttp 73832 6190477312 "GET /detail/2 HTTP/1.1" 500 59635
INFO 2023-10-02 03:33:35,640 autoreload 73832 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-02 03:33:35,976 autoreload 73866 8539431040 Watching for file changes with StatReloader
INFO 2023-10-02 03:33:36,473 basehttp 73866 6169866240 "GET /detail/2 HTTP/1.1" 200 934
INFO 2023-10-02 03:34:24,422 basehttp 73866 6169866240 "GET /detail/2 HTTP/1.1" 200 920
INFO 2023-10-02 03:34:46,488 basehttp 73866 6169866240 "GET /detail/2 HTTP/1.1" 200 978
INFO 2023-10-03 00:50:47,631 autoreload 99314 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 00:50:49,271 views 99314 6192787456 Result: home page access!
INFO 2023-10-03 00:50:49,286 basehttp 99314 6192787456 "GET / HTTP/1.1" 200 607
INFO 2023-10-03 00:50:54,167 basehttp 99314 6192787456 "GET /games HTTP/1.1" 301 0
ERROR 2023-10-03 00:50:54,204 log 99314 6192787456 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:50:54,207 basehttp 99314 6192787456 "GET /games/ HTTP/1.1" 500 90960
INFO 2023-10-03 00:53:14,647 autoreload 99314 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 00:53:15,039 autoreload 99585 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 00:55:44,450 autoreload 99585 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 00:55:44,807 autoreload 99753 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 00:55:46,547 views 99753 6130397184 Result: home page access!
INFO 2023-10-03 00:55:46,552 basehttp 99753 6130397184 "GET / HTTP/1.1" 200 607
ERROR 2023-10-03 00:55:57,173 log 99753 6130397184 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:55:57,176 basehttp 99753 6130397184 "GET /games/ HTTP/1.1" 500 90960
ERROR 2023-10-03 00:56:53,644 log 99753 6130397184 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:56:53,647 basehttp 99753 6130397184 "GET /games/ HTTP/1.1" 500 90960
ERROR 2023-10-03 00:56:55,177 log 99753 6130397184 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:56:55,180 basehttp 99753 6130397184 "GET /games/ HTTP/1.1" 500 90960
ERROR 2023-10-03 00:56:56,706 log 99753 6130397184 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:56:56,708 basehttp 99753 6130397184 "GET /games/ HTTP/1.1" 500 90960
INFO 2023-10-03 00:57:03,444 autoreload 99859 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 00:57:05,833 log 99859 6158299136 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 67, in render
    context = context or self.get_context()
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 358, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 732, in value_from_datadict
    getter = data.get
             ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR 2023-10-03 00:57:05,835 basehttp 99859 6158299136 "GET /games/ HTTP/1.1" 500 90960
INFO 2023-10-03 00:59:31,189 autoreload 99859 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 00:59:31,548 autoreload 169 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 00:59:35,532 log 169 6161903616 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/games_app/views.py", line 55, in games
    return render(request, 'games_app/games.html', {'form': form})
                                                            ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
ERROR 2023-10-03 00:59:35,533 basehttp 169 6161903616 "GET /games/ HTTP/1.1" 500 58382
INFO 2023-10-03 01:00:45,075 autoreload 169 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 01:00:45,447 autoreload 271 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:00:48,612 autoreload 271 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 01:00:48,858 autoreload 291 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 01:00:52,603 log 291 6203355136 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/games_app/views.py", line 55, in games
    return render(request, 'games_app/games.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: games_app/games.html
ERROR 2023-10-03 01:00:52,604 basehttp 291 6203355136 "GET /games/ HTTP/1.1" 500 73750
INFO 2023-10-03 01:01:38,939 autoreload 291 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp/apps.py changed, reloading.
INFO 2023-10-03 01:01:39,263 autoreload 379 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:02:09,944 autoreload 443 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:02:46,516 autoreload 443 8539431040 /Users/aleksey/Desktop/Django/Seminar/myproject/settings.py changed, reloading.
INFO 2023-10-03 01:02:46,854 autoreload 533 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 01:02:50,076 log 533 6171865088 Internal Server Error: /games/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: myapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/games_app/views.py", line 55, in games
    return render(request, 'games_app/games.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: myapp/base.html
ERROR 2023-10-03 01:02:50,078 basehttp 533 6171865088 "GET /games/ HTTP/1.1" 500 121917
INFO 2023-10-03 01:03:14,948 autoreload 584 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:03:18,951 basehttp 584 6162477056 "GET /games/ HTTP/1.1" 200 768
INFO 2023-10-03 01:04:16,222 autoreload 584 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/forms.py changed, reloading.
INFO 2023-10-03 01:04:16,604 autoreload 667 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:04:30,946 autoreload 667 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/forms.py changed, reloading.
INFO 2023-10-03 01:04:31,250 autoreload 705 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:05:22,403 basehttp 705 6203650048 "GET /games/ HTTP/1.1" 200 989
INFO 2023-10-03 01:06:29,561 basehttp 705 6203650048 "GET /games/ HTTP/1.1" 200 902
INFO 2023-10-03 01:06:33,645 views 705 6203650048 Получили name='E', count=4.
INFO 2023-10-03 01:06:33,649 basehttp 705 6203650048 "POST /games/ HTTP/1.1" 200 921
INFO 2023-10-03 01:31:43,595 autoreload 705 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 01:31:44,063 autoreload 2513 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:31:48,583 views 2513 6202945536 Получили name='E', count=4.
INFO 2023-10-03 01:31:48,602 basehttp 2513 6202945536 "POST /games/ HTTP/1.1" 200 921
INFO 2023-10-03 01:31:50,198 views 2513 6202945536 Получили name='E', count=4.
INFO 2023-10-03 01:31:50,207 basehttp 2513 6202945536 "POST /games/ HTTP/1.1" 200 921
INFO 2023-10-03 01:32:02,086 views 2513 6202945536 Получили name='E', count=4.
INFO 2023-10-03 01:32:02,095 basehttp 2513 6202945536 "POST /games/ HTTP/1.1" 200 921
INFO 2023-10-03 01:32:12,761 autoreload 2513 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 01:32:13,122 autoreload 2578 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:32:13,760 views 2578 6124236800 Получили name='E', count=4.
INFO 2023-10-03 01:32:13,780 basehttp 2578 6124236800 "POST /games/ HTTP/1.1" 200 921
INFO 2023-10-03 01:33:05,158 autoreload 2578 8539431040 /Users/aleksey/Desktop/Django/Seminar/games_app/views.py changed, reloading.
INFO 2023-10-03 01:33:05,535 autoreload 2645 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:33:06,003 views 2645 6138048512 Получили name='E', count=4.
INFO 2023-10-03 01:33:06,009 basehttp 2645 6138048512 "POST /games/ HTTP/1.1" 200 24
INFO 2023-10-03 01:39:54,343 autoreload 2645 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 01:39:54,689 autoreload 3159 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:50:01,137 autoreload 3159 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 01:50:01,494 autoreload 3946 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 01:50:15,611 basehttp 3946 6164705280 "GET /add_author HTTP/1.1" 301 0
INFO 2023-10-03 01:50:15,628 basehttp 3946 6164705280 "GET /add_author/ HTTP/1.1" 200 1314
INFO 2023-10-03 01:50:57,974 basehttp 3946 6164705280 "POST /add_author/ HTTP/1.1" 200 1382
INFO 2023-10-03 02:00:24,665 autoreload 3946 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-03 02:00:25,016 autoreload 4948 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:13:07,260 autoreload 4948 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-03 02:13:07,663 autoreload 5785 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:29:35,951 autoreload 5785 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:29:36,218 autoreload 6728 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:29:38,692 basehttp 6728 6198439936 "GET /add_author/ HTTP/1.1" 200 1320
INFO 2023-10-03 02:29:41,046 basehttp 6728 6198439936 "GET /add_author/ HTTP/1.1" 200 1320
INFO 2023-10-03 02:29:42,392 basehttp 6728 6198439936 "GET /add_article HTTP/1.1" 301 0
INFO 2023-10-03 02:29:42,407 basehttp 6728 6198439936 "GET /add_article/ HTTP/1.1" 200 1425
INFO 2023-10-03 02:32:25,037 autoreload 6728 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:32:25,304 autoreload 6950 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:32:31,582 basehttp 6950 6171930624 "GET /add_article/ HTTP/1.1" 200 1425
INFO 2023-10-03 02:34:29,998 basehttp 6950 6171930624 "GET /add_article/ HTTP/1.1" 200 1425
INFO 2023-10-03 02:34:30,504 autoreload 6950 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:34:30,781 autoreload 7101 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:34:32,630 basehttp 7101 6191214592 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:35:38,835 basehttp 7101 6191214592 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:35:38,994 autoreload 7101 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:35:39,289 autoreload 7204 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:36:16,010 autoreload 7204 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:36:16,295 autoreload 7256 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:36:36,662 autoreload 7256 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:36:36,907 autoreload 7285 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:36:52,135 autoreload 7285 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:36:52,401 autoreload 7318 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:38:29,808 autoreload 7318 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:38:30,092 autoreload 7451 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:39:04,754 autoreload 7451 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:39:05,053 autoreload 7511 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:39:20,381 autoreload 7511 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:39:20,627 autoreload 7539 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:39:21,447 basehttp 7539 6203240448 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:39:58,496 autoreload 7539 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:39:58,798 autoreload 7589 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:40:11,117 autoreload 7589 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:40:11,364 autoreload 7618 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:40:12,355 basehttp 7618 6123008000 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:40:17,431 basehttp 7618 6123008000 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:40:18,152 basehttp 7618 6123008000 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:40:19,263 basehttp 7618 6123008000 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:40:57,846 basehttp 7618 6123008000 "GET /add_article/ HTTP/1.1" 200 1413
INFO 2023-10-03 02:40:58,178 autoreload 7618 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:40:58,477 autoreload 7684 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:40:59,461 log 7684 6201880576 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 72, in article
    return render(request, 'myapp2/add_article.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 94, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 269, in build_widget_attrs
    widget.use_required_attribute(self.initial)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 783, in use_required_attribute
    and self._choice_has_empty_value(first_choice)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 766, in _choice_has_empty_value
    value, _ = choice
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
ERROR 2023-10-03 02:40:59,466 basehttp 7684 6201880576 "GET /add_article/ HTTP/1.1" 500 245246
ERROR 2023-10-03 02:41:13,636 log 7684 6201880576 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 72, in article
    return render(request, 'myapp2/add_article.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 94, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 269, in build_widget_attrs
    widget.use_required_attribute(self.initial)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 783, in use_required_attribute
    and self._choice_has_empty_value(first_choice)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 766, in _choice_has_empty_value
    value, _ = choice
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
ERROR 2023-10-03 02:41:13,639 basehttp 7684 6201880576 "GET /add_article/ HTTP/1.1" 500 245246
INFO 2023-10-03 02:41:32,226 autoreload 7684 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:41:32,528 autoreload 7731 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:41:34,019 log 7731 6167064576 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 72, in article
    return render(request, 'myapp2/add_article.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 94, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 269, in build_widget_attrs
    widget.use_required_attribute(self.initial)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 783, in use_required_attribute
    and self._choice_has_empty_value(first_choice)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 766, in _choice_has_empty_value
    value, _ = choice
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
ERROR 2023-10-03 02:41:34,024 basehttp 7731 6167064576 "GET /add_article/ HTTP/1.1" 500 245630
ERROR 2023-10-03 02:41:37,331 log 7731 6167064576 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 72, in article
    return render(request, 'myapp2/add_article.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 94, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 269, in build_widget_attrs
    widget.use_required_attribute(self.initial)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 783, in use_required_attribute
    and self._choice_has_empty_value(first_choice)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 766, in _choice_has_empty_value
    value, _ = choice
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
ERROR 2023-10-03 02:41:37,335 basehttp 7731 6167064576 "GET /add_article/ HTTP/1.1" 500 245630
ERROR 2023-10-03 02:41:52,869 log 7731 6167064576 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 72, in article
    return render(request, 'myapp2/add_article.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 94, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/boundfield.py", line 269, in build_widget_attrs
    widget.use_required_attribute(self.initial)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 783, in use_required_attribute
    and self._choice_has_empty_value(first_choice)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/forms/widgets.py", line 766, in _choice_has_empty_value
    value, _ = choice
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
ERROR 2023-10-03 02:41:52,873 basehttp 7731 6167064576 "GET /add_article/ HTTP/1.1" 500 245630
INFO 2023-10-03 02:41:53,115 autoreload 7731 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:41:53,370 autoreload 7765 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:41:56,182 basehttp 7765 6162608128 "GET /add_article/ HTTP/1.1" 200 2217
INFO 2023-10-03 02:45:52,255 autoreload 7765 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:45:52,541 autoreload 8068 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:46:00,993 basehttp 8068 6192148480 "GET /add_article/ HTTP/1.1" 200 2087
ERROR 2023-10-03 02:46:07,482 log 8068 6192148480 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:46:07,483 basehttp 8068 6192148480 "POST /add_article/ HTTP/1.1" 500 61375
INFO 2023-10-03 02:46:35,512 autoreload 8068 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:46:35,818 autoreload 8127 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:46:36,260 log 8127 6132936704 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:46:36,261 basehttp 8127 6132936704 "POST /add_article/ HTTP/1.1" 500 61371
INFO 2023-10-03 02:46:52,205 autoreload 8127 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:46:52,423 autoreload 8163 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:46:53,563 log 8163 6195851264 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:46:53,563 basehttp 8163 6195851264 "POST /add_article/ HTTP/1.1" 500 61399
INFO 2023-10-03 02:47:19,109 autoreload 8163 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:47:19,393 autoreload 8206 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:47:20,671 log 8206 6165377024 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:47:20,672 basehttp 8206 6165377024 "POST /add_article/ HTTP/1.1" 500 61405
ERROR 2023-10-03 02:47:27,710 log 8206 6165377024 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:47:27,711 basehttp 8206 6165377024 "POST /add_article/ HTTP/1.1" 500 61405
ERROR 2023-10-03 02:47:33,777 log 8206 6165377024 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:47:33,779 basehttp 8206 6165377024 "POST /add_article/ HTTP/1.1" 500 61405
INFO 2023-10-03 02:47:48,052 autoreload 8206 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:47:48,293 autoreload 8249 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:47:49,517 log 8249 6196310016 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:47:49,517 basehttp 8249 6196310016 "POST /add_article/ HTTP/1.1" 500 61405
ERROR 2023-10-03 02:47:53,152 log 8249 6196310016 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:47:53,153 basehttp 8249 6196310016 "POST /add_article/ HTTP/1.1" 500 61405
INFO 2023-10-03 02:48:23,278 basehttp 8249 6196310016 "GET /add_article/ HTTP/1.1" 200 2087
ERROR 2023-10-03 02:48:30,146 log 8249 6196310016 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 58, in article
    author_id = form.cleaned_data['author_id']
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'author_id'
ERROR 2023-10-03 02:48:30,147 basehttp 8249 6196310016 "POST /add_article/ HTTP/1.1" 500 61400
INFO 2023-10-03 02:49:10,061 autoreload 8249 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:49:10,329 autoreload 8349 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:49:11,408 basehttp 8349 6169980928 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:49:34,869 autoreload 8349 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:49:35,137 autoreload 8409 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:49:38,892 basehttp 8409 6192279552 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:49:50,550 autoreload 8409 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/forms.py changed, reloading.
INFO 2023-10-03 02:49:50,815 autoreload 8437 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:49:55,407 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:49:57,974 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:49:59,141 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:50:00,047 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:50:01,000 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:50:01,787 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:50:02,580 basehttp 8437 6125154304 "POST /add_article/ HTTP/1.1" 200 2146
INFO 2023-10-03 02:50:25,569 autoreload 8437 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:50:25,848 autoreload 8495 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:50:27,909 log 8495 6169374720 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 62, in article
    article = Article(title=title,
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "1": "Article.author_id" must be a "Author" instance.
ERROR 2023-10-03 02:50:27,911 basehttp 8495 6169374720 "POST /add_article/ HTTP/1.1" 500 72437
INFO 2023-10-03 02:52:12,737 autoreload 8653 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:52:22,216 autoreload 8670 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:52:43,659 autoreload 8699 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:53:15,104 autoreload 8743 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:53:16,905 autoreload 8752 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:53:26,328 autoreload 8769 8539431040 Watching for file changes with StatReloader
WARNING 2023-10-03 02:53:28,364 log 8769 6137802752 Not Found: /
WARNING 2023-10-03 02:53:28,364 basehttp 8769 6137802752 "GET / HTTP/1.1" 404 4596
WARNING 2023-10-03 02:53:28,452 log 8769 6137802752 Not Found: /favicon.ico
WARNING 2023-10-03 02:53:28,452 basehttp 8769 6137802752 "GET /favicon.ico HTTP/1.1" 404 4647
INFO 2023-10-03 02:53:43,834 basehttp 8769 6137802752 "GET /add_article HTTP/1.1" 301 0
INFO 2023-10-03 02:53:43,858 basehttp 8769 6137802752 "GET /add_article/ HTTP/1.1" 200 2087
ERROR 2023-10-03 02:53:49,117 log 8769 6137802752 Internal Server Error: /add_article/
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 62, in article
    article = Article(title=title,
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<Article: title: Title1,description: Text from firstname1 lastname1  # 1 is bla bla bla many long text,create_at: 2023-09-29 07:49:36.418069+00:00,author_id" Author object (6),category: category1,views: 20,publish: False>": "Article.author_id" must be a "Author" instance.
ERROR 2023-10-03 02:53:49,119 basehttp 8769 6137802752 "POST /add_article/ HTTP/1.1" 500 74274
INFO 2023-10-03 02:54:08,392 autoreload 8769 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:54:08,680 autoreload 8834 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:54:09,069 basehttp 8834 6164393984 "POST /add_article/ HTTP/1.1" 200 2149
INFO 2023-10-03 02:54:18,097 basehttp 8834 6164393984 "POST /add_article/ HTTP/1.1" 200 2149
INFO 2023-10-03 02:55:45,887 basehttp 8834 6164393984 "POST /add_article/ HTTP/1.1" 200 2149
INFO 2023-10-03 02:55:47,287 basehttp 8834 6164393984 "POST /add_article/ HTTP/1.1" 200 2149
INFO 2023-10-03 02:56:39,377 basehttp 8834 6164393984 "GET /add_article/ HTTP/1.1" 200 2087
INFO 2023-10-03 02:56:41,786 basehttp 8834 6164393984 "GET /add_article/ HTTP/1.1" 200 2087
ERROR 2023-10-03 02:56:45,881 log 8834 6164393984 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'games_app/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: games_app/index.html
ERROR 2023-10-03 02:56:45,882 basehttp 8834 6164393984 "GET /articles/1 HTTP/1.1" 500 78046
ERROR 2023-10-03 02:57:09,443 log 8834 6164393984 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'games_app/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: games_app/index.html
ERROR 2023-10-03 02:57:09,444 basehttp 8834 6164393984 "GET /articles/1 HTTP/1.1" 500 78046
INFO 2023-10-03 02:57:10,562 basehttp 8834 6164393984 "GET /add_article/ HTTP/1.1" 200 2087
ERROR 2023-10-03 02:57:11,281 log 8834 6164393984 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'games_app/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: games_app/index.html
ERROR 2023-10-03 02:57:11,282 basehttp 8834 6164393984 "GET /articles/1 HTTP/1.1" 500 78046
INFO 2023-10-03 02:57:54,407 autoreload 8834 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:57:54,793 autoreload 9078 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:57:54,985 log 9078 6137950208 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-03 02:57:54,986 basehttp 9078 6137950208 "GET /articles/1 HTTP/1.1" 500 77966
INFO 2023-10-03 02:59:03,013 autoreload 9078 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:59:03,285 autoreload 9164 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 02:59:26,666 autoreload 9164 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 02:59:26,894 autoreload 9199 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 02:59:27,528 log 9199 6192459776 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-03 02:59:27,529 basehttp 9199 6192459776 "GET /articles/1 HTTP/1.1" 500 77966
INFO 2023-10-03 03:00:16,908 autoreload 9199 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/urls.py changed, reloading.
INFO 2023-10-03 03:00:17,219 autoreload 9266 8539431040 Watching for file changes with StatReloader
ERROR 2023-10-03 03:00:17,898 log 9266 6157103104 Internal Server Error: /articles/1
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 15, in get_articles
    return render(request, 'myapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/index.html
ERROR 2023-10-03 03:00:17,899 basehttp 9266 6157103104 "GET /articles/1 HTTP/1.1" 500 77966
INFO 2023-10-03 03:01:12,208 autoreload 9266 8539431040 /Users/aleksey/Desktop/Django/Seminar/myapp2/views.py changed, reloading.
INFO 2023-10-03 03:01:12,469 autoreload 9352 8539431040 Watching for file changes with StatReloader
INFO 2023-10-03 03:01:14,489 basehttp 9352 6170144768 "GET /articles/1 HTTP/1.1" 200 1067
ERROR 2023-10-03 03:01:26,325 log 9352 6170144768 Internal Server Error: /detail/101
Traceback (most recent call last):
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/myapp2/views.py", line 28, in detail_articles
    return render(request, 'myapp/about.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksey/Desktop/Django/Seminar/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/about.html
ERROR 2023-10-03 03:01:26,326 basehttp 9352 6170144768 "GET /detail/101 HTTP/1.1" 500 76231
INFO 2023-10-03 03:01:36,208 basehttp 9352 6170144768 "GET /articles/1 HTTP/1.1" 200 1067
INFO 2023-10-03 03:01:36,563 basehttp 9352 6170144768 "GET /articles/2 HTTP/1.1" 200 603
INFO 2023-10-03 03:01:39,615 basehttp 9352 6170144768 "GET /articles/2 HTTP/1.1" 200 603
INFO 2023-10-03 03:01:40,034 basehttp 9352 6170144768 "GET /articles/3 HTTP/1.1" 200 603
INFO 2023-10-03 03:01:43,505 basehttp 9352 6170144768 "GET /articles/3 HTTP/1.1" 200 603
INFO 2023-10-03 03:01:44,061 basehttp 9352 6170144768 "GET /articles/5 HTTP/1.1" 200 603
INFO 2023-10-03 03:02:08,523 basehttp 9352 6170144768 "GET /articles/5 HTTP/1.1" 200 603
INFO 2023-10-03 03:02:08,644 basehttp 9352 6170144768 "GET /articles/1 HTTP/1.1" 200 1067
INFO 2023-10-03 03:02:33,637 basehttp 9352 6170144768 "GET /articles/5 HTTP/1.1" 200 603
INFO 2023-10-03 03:02:34,076 basehttp 9352 6170144768 "GET /articles/6 HTTP/1.1" 200 2203
INFO 2023-10-03 03:02:38,140 basehttp 9352 6170144768 "GET /articles/6 HTTP/1.1" 200 2203
INFO 2023-10-03 03:02:38,446 basehttp 9352 6170144768 "GET /articles/1 HTTP/1.1" 200 1067
INFO 2023-10-03 03:03:37,487 autoreload 9516 8539431040 Watching for file changes with StatReloader
